apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-client
  namespace: secure-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-client
  template:
    metadata:
      labels:
        app: secure-client
    spec:
      serviceAccountName: sa-secure-storage
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: client
        image: busybox:1.35
        command: ["sleep", "3600"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: tmp-volume
          mountPath: /tmp
        env:
        - name: DB_HOST
          value: "secure-database"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-storage
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
  namespace: secure-storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: encrypted-ssd
  resources:
    requests:
      storage: 5Gi