apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-app-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: production
  source:
    repoURL: https://github.com/your-org/secure-app-config
    targetRevision: v1.0.0  # Tag stable pour prod
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-app-prod
  syncPolicy:
    # Pas d'auto-sync en prod - déploiement manuel
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10