apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: rolling-update-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Rolling Update Demo</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                text-align: center; 
                background-color: #e3f2fd;
                padding: 50px;
            }
            .version { 
                color: #1976d2; 
                font-size: 2em; 
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <h1>Application Web - Rolling Update Demo</h1>
        <div class="version">Version: 1.0</div>
        <p>Hostname: <span id="hostname"></span></p>
        <p>Timestamp: <span id="timestamp"></span></p>
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
            document.getElementById('timestamp').textContent = new Date().toISOString();
            // Refresh timestamp every second
            setInterval(() => {
                document.getElementById('timestamp').textContent = new Date().toISOString();
            }, 1000);
        </script>
    </body>
    </html>